defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: root
  encoding: utf8
  pool: 5
  reconnect: false

development:
  <<: *defaults
  database: fruitwood_development

test:
  <<: *defaults
  database: fruitwood_test

production:
  <<: *defaults
  database: fruitwood
